// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: api/groupi.proto

package group

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckDailyProgressSeasonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeCheck *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time_check,json=timeCheck,proto3" json:"time_check,omitempty"`
}

func (x *CheckDailyProgressSeasonRequest) Reset() {
	*x = CheckDailyProgressSeasonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_groupi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckDailyProgressSeasonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDailyProgressSeasonRequest) ProtoMessage() {}

func (x *CheckDailyProgressSeasonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_groupi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDailyProgressSeasonRequest.ProtoReflect.Descriptor instead.
func (*CheckDailyProgressSeasonRequest) Descriptor() ([]byte, []int) {
	return file_api_groupi_proto_rawDescGZIP(), []int{0}
}

func (x *CheckDailyProgressSeasonRequest) GetTimeCheck() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeCheck
	}
	return nil
}

type CheckDailyProgressSeasonReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CheckDailyProgressSeasonReply) Reset() {
	*x = CheckDailyProgressSeasonReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_groupi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckDailyProgressSeasonReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDailyProgressSeasonReply) ProtoMessage() {}

func (x *CheckDailyProgressSeasonReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_groupi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDailyProgressSeasonReply.ProtoReflect.Descriptor instead.
func (*CheckDailyProgressSeasonReply) Descriptor() ([]byte, []int) {
	return file_api_groupi_proto_rawDescGZIP(), []int{1}
}

type CheckDailyProgressChallengeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimeCheck *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time_check,json=timeCheck,proto3" json:"time_check,omitempty"`
}

func (x *CheckDailyProgressChallengeRequest) Reset() {
	*x = CheckDailyProgressChallengeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_groupi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckDailyProgressChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDailyProgressChallengeRequest) ProtoMessage() {}

func (x *CheckDailyProgressChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_groupi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDailyProgressChallengeRequest.ProtoReflect.Descriptor instead.
func (*CheckDailyProgressChallengeRequest) Descriptor() ([]byte, []int) {
	return file_api_groupi_proto_rawDescGZIP(), []int{2}
}

func (x *CheckDailyProgressChallengeRequest) GetTimeCheck() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeCheck
	}
	return nil
}

type CheckDailyProgressChallengeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CheckDailyProgressChallengeReply) Reset() {
	*x = CheckDailyProgressChallengeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_groupi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckDailyProgressChallengeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDailyProgressChallengeReply) ProtoMessage() {}

func (x *CheckDailyProgressChallengeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_groupi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDailyProgressChallengeReply.ProtoReflect.Descriptor instead.
func (*CheckDailyProgressChallengeReply) Descriptor() ([]byte, []int) {
	return file_api_groupi_proto_rawDescGZIP(), []int{3}
}

type UpdateChallengeProgressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChallengeId    int64                  `protobuf:"varint,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	UserId         int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Time           *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	ActivityRecord *ActivityRecord        `protobuf:"bytes,4,opt,name=activityRecord,proto3" json:"activityRecord,omitempty"`
}

func (x *UpdateChallengeProgressRequest) Reset() {
	*x = UpdateChallengeProgressRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_groupi_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateChallengeProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChallengeProgressRequest) ProtoMessage() {}

func (x *UpdateChallengeProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_groupi_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChallengeProgressRequest.ProtoReflect.Descriptor instead.
func (*UpdateChallengeProgressRequest) Descriptor() ([]byte, []int) {
	return file_api_groupi_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateChallengeProgressRequest) GetChallengeId() int64 {
	if x != nil {
		return x.ChallengeId
	}
	return 0
}

func (x *UpdateChallengeProgressRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateChallengeProgressRequest) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *UpdateChallengeProgressRequest) GetActivityRecord() *ActivityRecord {
	if x != nil {
		return x.ActivityRecord
	}
	return nil
}

// Including increment values needed to update challenge member rules
type ActivityRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CaloriesValue  int64 `protobuf:"varint,1,opt,name=calories_value,json=caloriesValue,proto3" json:"calories_value,omitempty"`
	TimeSpendValue int64 `protobuf:"varint,2,opt,name=time_spend_value,json=timeSpendValue,proto3" json:"time_spend_value,omitempty"`
	DistanceValue  int64 `protobuf:"varint,3,opt,name=distance_value,json=distanceValue,proto3" json:"distance_value,omitempty"`
}

func (x *ActivityRecord) Reset() {
	*x = ActivityRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_groupi_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivityRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityRecord) ProtoMessage() {}

func (x *ActivityRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_groupi_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityRecord.ProtoReflect.Descriptor instead.
func (*ActivityRecord) Descriptor() ([]byte, []int) {
	return file_api_groupi_proto_rawDescGZIP(), []int{5}
}

func (x *ActivityRecord) GetCaloriesValue() int64 {
	if x != nil {
		return x.CaloriesValue
	}
	return 0
}

func (x *ActivityRecord) GetTimeSpendValue() int64 {
	if x != nil {
		return x.TimeSpendValue
	}
	return 0
}

func (x *ActivityRecord) GetDistanceValue() int64 {
	if x != nil {
		return x.DistanceValue
	}
	return 0
}

type UpdateChallengeProgressReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateChallengeProgressReply) Reset() {
	*x = UpdateChallengeProgressReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_groupi_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateChallengeProgressReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChallengeProgressReply) ProtoMessage() {}

func (x *UpdateChallengeProgressReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_groupi_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChallengeProgressReply.ProtoReflect.Descriptor instead.
func (*UpdateChallengeProgressReply) Descriptor() ([]byte, []int) {
	return file_api_groupi_proto_rawDescGZIP(), []int{6}
}

var File_api_groupi_proto protoreflect.FileDescriptor

var file_api_groupi_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5c, 0x0a, 0x1f, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a,
	0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x22, 0x1f, 0x0a, 0x1d, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x53, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x5f, 0x0a, 0x22, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x43,
	0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x39, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x22, 0x22, 0x0a, 0x20, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0xcb,
	0x01, 0x0a, 0x1e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e,
	0x67, 0x65, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e,
	0x67, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2e, 0x0a,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x3d, 0x0a,
	0x0e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x0e, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x22, 0x88, 0x01, 0x0a,
	0x0e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12,
	0x25, 0x0a, 0x0e, 0x63, 0x61, 0x6c, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x63, 0x61, 0x6c, 0x6f, 0x72, 0x69, 0x65,
	0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73,
	0x70, 0x65, 0x6e, 0x64, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x70, 0x65, 0x6e, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x25, 0x0a, 0x0e, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1e, 0x0a, 0x1c, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65,
	0x73, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xcc, 0x02, 0x0a, 0x06, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x12, 0x65, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6c,
	0x6c, 0x65, 0x6e, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x25, 0x2e,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6c,
	0x6c, 0x65, 0x6e, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x67,
	0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x71, 0x0a, 0x1b, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x43,
	0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x12, 0x29, 0x2e, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x50, 0x72, 0x6f, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x43, 0x68,
	0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x68, 0x0a, 0x18,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65,
	0x73, 0x73, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x26, 0x2e, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x50, 0x72, 0x6f, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x24, 0x2e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44, 0x61,
	0x69, 0x6c, 0x79, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x53, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x6e, 0x68, 0x72, 0x65, 0x76, 0x2f, 0x72, 0x75, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x3b, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_groupi_proto_rawDescOnce sync.Once
	file_api_groupi_proto_rawDescData = file_api_groupi_proto_rawDesc
)

func file_api_groupi_proto_rawDescGZIP() []byte {
	file_api_groupi_proto_rawDescOnce.Do(func() {
		file_api_groupi_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_groupi_proto_rawDescData)
	})
	return file_api_groupi_proto_rawDescData
}

var file_api_groupi_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_groupi_proto_goTypes = []interface{}{
	(*CheckDailyProgressSeasonRequest)(nil),    // 0: group.CheckDailyProgressSeasonRequest
	(*CheckDailyProgressSeasonReply)(nil),      // 1: group.CheckDailyProgressSeasonReply
	(*CheckDailyProgressChallengeRequest)(nil), // 2: group.CheckDailyProgressChallengeRequest
	(*CheckDailyProgressChallengeReply)(nil),   // 3: group.CheckDailyProgressChallengeReply
	(*UpdateChallengeProgressRequest)(nil),     // 4: group.UpdateChallengeProgressRequest
	(*ActivityRecord)(nil),                     // 5: group.ActivityRecord
	(*UpdateChallengeProgressReply)(nil),       // 6: group.UpdateChallengeProgressReply
	(*timestamppb.Timestamp)(nil),              // 7: google.protobuf.Timestamp
}
var file_api_groupi_proto_depIdxs = []int32{
	7, // 0: group.CheckDailyProgressSeasonRequest.time_check:type_name -> google.protobuf.Timestamp
	7, // 1: group.CheckDailyProgressChallengeRequest.time_check:type_name -> google.protobuf.Timestamp
	7, // 2: group.UpdateChallengeProgressRequest.time:type_name -> google.protobuf.Timestamp
	5, // 3: group.UpdateChallengeProgressRequest.activityRecord:type_name -> group.ActivityRecord
	4, // 4: group.GroupI.UpdateChallengeProgress:input_type -> group.UpdateChallengeProgressRequest
	2, // 5: group.GroupI.CheckDailyProgressChallenge:input_type -> group.CheckDailyProgressChallengeRequest
	0, // 6: group.GroupI.CheckDailyProgressSeason:input_type -> group.CheckDailyProgressSeasonRequest
	6, // 7: group.GroupI.UpdateChallengeProgress:output_type -> group.UpdateChallengeProgressReply
	3, // 8: group.GroupI.CheckDailyProgressChallenge:output_type -> group.CheckDailyProgressChallengeReply
	1, // 9: group.GroupI.CheckDailyProgressSeason:output_type -> group.CheckDailyProgressSeasonReply
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_groupi_proto_init() }
func file_api_groupi_proto_init() {
	if File_api_groupi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_groupi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckDailyProgressSeasonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_groupi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckDailyProgressSeasonReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_groupi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckDailyProgressChallengeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_groupi_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckDailyProgressChallengeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_groupi_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateChallengeProgressRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_groupi_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivityRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_groupi_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateChallengeProgressReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_groupi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_groupi_proto_goTypes,
		DependencyIndexes: file_api_groupi_proto_depIdxs,
		MessageInfos:      file_api_groupi_proto_msgTypes,
	}.Build()
	File_api_groupi_proto = out.File
	file_api_groupi_proto_rawDesc = nil
	file_api_groupi_proto_goTypes = nil
	file_api_groupi_proto_depIdxs = nil
}
