version: '3.7'

services:
  sample:
    build:
      context: backend/sample
      dockerfile: build/Dockerfile
    container_name: sample

  caller:
    build:
      context: backend/caller
      dockerfile: build/Dockerfile
    container_name: caller

  gateway:
    build:
      context: backend/gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - 8080:8080
  
  auth:
    build:
      context: backend/auth
      dockerfile: build/Dockerfile
    container_name: auth
