version: '3.7'

services:
  sample:
    build:
      context: backend/sample
      dockerfile: build/Dockerfile
    container_name: sample
    ports:
      - 8082:8080

  caller:
    build:
      context: backend/caller
      dockerfile: build/Dockerfile
    container_name: caller
    ports:
      - 8081:8080