version: '3.7'

services:
  gateway:
    build:
      context: backend/gateway
      dockerfile: Dockerfile
    container_name: gateway
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - 8080:8080
  auth:
    build:
      context: backend/auth
      dockerfile: Dockerfile
    container_name: auth
    volumes:
      - ./backend/auth:/app
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    depends_on:
      - auth_db
      - redis
    environment:
      LISTEN_PORT: 8080
      DB_USERNAME: root
      DB_PASSWORD: password@1
      DB_HOST: auth_db
      DB_PORT: 3306
      DB_NAME: auth
      NOTIFICATION_SERVICE: notification
      NOTIFICATION_PORT: 8080
      CACHE_HOST: redis
      CACHE_PORT: 6379
      CACHE_PASSWORD: ""
      CACHE_DB: 0
      IS_SECURE_CONNECTION: "false"

  group:
    build:
      context: backend/group
      dockerfile: Dockerfile
    container_name: group
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    depends_on:
      - group_db
    environment:
      LISTEN_PORT: 8080
      DB_USERNAME: root
      DB_PASSWORD: password@1
      DB_HOST: group_db
      DB_PORT: 3306
      DB_NAME: group
      AUTH_SERVICE: auth
      AUTH_PORT: 8080
      IS_SECURE_CONNECTION: "false"
      NOTIFICATION_SERVICE: notification
      NOTIFICATION_PORT: 8080

  activity:
    build:
      context: backend/activity
      dockerfile: Dockerfile
    container_name: activity
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    depends_on:
      - activity_db
    environment:
      LISTEN_PORT: 8080
      DB_USERNAME: root
      DB_PASSWORD: password@1
      DB_HOST: activity_db
      DB_PORT: 3306
      DB_NAME: activity
      PLANI_DOMAIN: plan
      PLANI_PORT: 8080
      GROUPI_DOMAIN: group
      GROUPI_PORT: 8080
      IS_SECURE_CONNECTION: "false"

  notification:
    build:
      context: backend/notification
      dockerfile: Dockerfile
    container_name: notification
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    depends_on:
      - notification_db
    environment:
      LISTEN_PORT: 8080
      DB_USERNAME: root
      DB_PASSWORD: password@1
      DB_HOST: notification_db
      DB_PORT: 3306
      DB_NAME: notification
      AUTH_SERVICE: auth
      AUTH_PORT: 8080
      GCP_CLOUD_TASK_HOST: gcloud-tasks-emulator
      GCP_CLOUD_TASK_PORT: 8123
      GCP_CLOUD_TASK_PROJECT_ID: daring-acumen-370401
      GCP_CLOUD_TASK_LOCATION_ID: asia-southeast2
      GCP_CLOUD_TASK_QUEUE_ID: test-queue1
      # GCP_CLOUD_TASK_PROJECT_ID: new-runtracking
      # GCP_CLOUD_TASK_LOCATION_ID: asia-southeast1
      # GCP_CLOUD_TASK_QUEUE_ID: notification
      IS_SECURE_CONNECTION: "false"
      INTERMEDIARY_SCHEME: http
      INTERMEDIARY_URL: intermediary:8080
      ENVIROMENT_MODE: local

  intermediary:
    build:
      context: backend/intermediary
      dockerfile: Dockerfile
    container_name: intermediary
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    depends_on:
      - notification_db
    environment:
      LISTEN_HTTP_PORT: 8080
      DB_USERNAME: root
      DB_PASSWORD: password@1
      DB_HOST: notification_db
      DB_PORT: 3306
      DB_NAME: notification
      AUTH_SERVICE: auth
      AUTH_PORT: 8080
      PLAN_SERVICE: plan
      PLAN_PORT: 8080
      IS_SECURE_CONNECTION: "false"
      GROUP_SERVICE: group
      GROUP_PORT: 8080
    ports:
      - 8082:8080
  # umage:
  #   build:
  #     context: backend/umage
  #     dockerfile: Dockerfile
  #   container_name: umage
  #   environment:
  #     KEY: "ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAibmV3LXJ1bnRyYWNraW5nIiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiYzNmMWE4Y2RlZDVmOGQzNzdiYTJlMWE1YWRjYTgwOWYwZWJiNzAyNSIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZnSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2d3Z2dTa0FnRUFBb0lCQVFENkN0akhLeXJLN3RRMVxuK0luK0prYkgxdWlud0NuWnQ2SlV4bkxTRnBmbEx5MlN5ZDc2a0plZGNXYTV2VExaOVZBZ2xrK3RidzBCbm12QVxuQi8zOWVlbkVGMzAxeE5Zc0RLOE9jN2hkRVIvRXRabVYrVWNodkhJblpGUnBNYjY4SDY3dHZoQVZaWnczc1VqM1xuTW9Bb2JWVHMvTlRlK1lCZDVRbzZ4K25MenF6THlzZWd0N05OQmlOQ2hLQ2RuSzhMRFdOWkJXZ3ZVQjl2VEZQZ1xuMUdNSk4yWkZ0ZGZMem9QRVVVck5Mb29vc242M3ZxM0lyVGN0RkxOQThWT2FsZHY3SklZRWp6Um1Jd1A3TTNPU1xuZkxxZXZOS1hiYm5sRFB4VzA4U3BiY0grb2ZRcWlMRWhJc0ZXZUdQOUI0eURHbnNZZGdPc0l6MWZaNG1iMll1cFxuQkNFUDkxWkRBZ01CQUFFQ2dnRUFDbm1ldm1XLzVXcS9GOWd0Nm0rU1M0bldicTdpNTBrd0tITzFOUTZlbGZ4OFxucUE2OGg0K2ZuREx3TzNFZXlySlVCVDdON1lBZW5IdHF4dG5WK1g5bkhGME00dXFxSHk2L0VrSmVZQUpxK2hJSFxueDVod3dWTVBEdi9iZHNTNkVtMU03VGxEbkpBV3ZxYU1RWTBkSzVSbk5OcmptNnZCaFo5Q2tjaThCMXJoYTZrRlxuUUp5cXdRaHdzUDlLRzVqNy9KemhkeWpzTlRST3J2cHZhdUxGcFFhMUlkT0RWSllaMS80QWlBQnVZUEJ6dWZnSFxuQXAveDY1d0FybkRGY1NINGRDbmx1USt5V2xUQjhmZzBHaHFqa3dzODJnZkpKeHVuWUp1N0JYSkFMWEJqU3pkMFxuaXZvRWlQYUNTVEMzekowTHFrWUFUN2pYdE5NNDZkVllNZEpnL3h4S2tRS0JnUUQrS0R6RFVLZ3BnNCtNUDJPa1xuU2MwUTdsSEVlcjVKcjNzUGM3R0N4S1JXY2JYLzdYaUIyZTBzQUlYcCtsYmtnRkhkYVFXcXlhbnpOQUVxdVh6b1xuMHhkeHkwNE1QZjZEaytUSGdUTjMrV3lXaTFaZUlGY2xDNmdCOHlFL3NpQWhHMXB1RkdzY2d4NGFCcXBDWGRFbVxuMnNsdXdLL0ZkcHc5amsvK0hSaUJjRWk2SlFLQmdRRDcydmk2U1RDL2ZjWGJ3cDFlQnEvcUcxUElyZWx1TERSMVxuemRkWG9zeHI5cFZyVTNXQTl0RWt1YUZyeHAzTjFVWmoxMzZ0cjZJMlVvd2gvUVZvVytieGdyTThVS3Z5REk4YlxuRkVpZ2xIbVUxd3pEZm5uYUM3UnMxei84emtuRkREc1JuTEU1Z1ozOWZhaFpuN29sYWd2OFlhMXFGQk5ETmVCalxucW1OVTVELytSd0tCZ0M0KytoZDhGSzFCSUJ5ZjZDeWJ0VEd3ZTdacHN6aExNdlF6MUFmOGFmN0V3QjRxZ3JQMlxuQ0g3cU5YUEd0b3JyZ25uc1F6aTVhekF5dFVlbDZzR2VyM1JvVHZKUlVYOTFxTHBZbXhub2k4YTA0ZWxNcnk2eFxuZVVlcGl0SkJRakZqL2NkcjliV0JjamZBSUxqa3cwcnpvcFdCZ0RwSkE5TDdremlrNkxHYzBjNzFBb0dCQVBmdlxuZ0M2N2dLN3kzVVpUbDJJS0NVSFpOeWoyOURjT2MzS0plblgrZ1duRGJTTWtIU2doVXBEcDRaeGRBZHF4RzhPTVxuVUZ3aDYvbTRWOVhaNVdud0Z6RW9MdFN3d2lUZDhqK0JQMkk5NkZiN1FjaHVpUHg3eTFuZXFWSnhyak82cjZmTlxuN3JZakFPcWN1by9JYTVNTGk5TWdRWHlOV00wd2k3N3g3U21VTGQ5ZkFvR0JBSm5kLy9WTzMwSTJRRTVNc2JzR1xuZktFM3NpUGQ5M1JrazVhY0lxMkxsZU9XbUlqRWtCdnBjYkNMM0ZIRVpjRmVZNit3ZzZwUENWVG9sb053RmFUTVxud2diRU55UytEVWRob0I5V2NqZUpxdFQzYzRnYzZ5L3JvRTQ3WUxIY0VJWmVkK3VUUTBDSnp5eUFHMEc5REpaNFxuRHh0eHBmajdwbWZaNkFvWVY4VlJFSmlHXG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAiYnVja2V0LXNlcnZpY2VAbmV3LXJ1bnRyYWNraW5nLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjEwNDkxMzMyOTA2NTE5ODY2NzE4NyIsCiAgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwKICAidG9rZW5fdXJpIjogImh0dHBzOi8vb2F1dGgyLmdvb2dsZWFwaXMuY29tL3Rva2VuIiwKICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsCiAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvYnVja2V0LXNlcnZpY2UlNDBuZXctcnVudHJhY2tpbmcuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iCn0K"

  plan:
    build:
      context: backend/plan
      dockerfile: Dockerfile
    container_name: plan
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    depends_on:
      - plan_db
    ports:
      - 8081:8080
    environment:
      LISTEN_PORT: 8080
      DB_USERNAME: root
      DB_PASSWORD: password@1
      DB_HOST: plan_db
      DB_PORT: 3306
      DB_NAME: plan
      NOTIFICATIONI_DOMAIN: notification
      NOTIFICATIONI_PORT: 8080
      IS_SECURE_CONNECTION: "false"

  chat:
    build:
      context: backend/chat
      dockerfile: Dockerfile
    container_name: chat
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    depends_on:
      - chat_db
    ports:
      - 8088:8080
    environment:
      LISTEN_PORT: 8080
      DB_USERNAME: root
      DB_PASSWORD: password@1
      DB_HOST: chat_db
      DB_PORT: 3306
      DB_NAME: chat
      AUTH_SERVICE: auth
      AUTH_PORT: 8080
      NOTIFICATION_SERVICE: notification
      NOTIFICATION_PORT: 8080
      # GCP_CLOUD_TASK_PROJECT_ID: new-runtracking
      # GCP_CLOUD_TASK_LOCATION_ID: asia-southeast1
      # GCP_CLOUD_TASK_QUEUE_ID: notification
      IS_SECURE_CONNECTION: "false"

  gcloud-tasks-emulator:
    image: ghcr.io/aertje/cloud-tasks-emulator:latest
    command: -host 0.0.0.0 -port 8123 -queue "projects/daring-acumen-370401/locations/asia-southeast2/queues/test-queue1"
    ports:
      - "${TASKS_PORT:-8123}:8123"
    environment:
      APP_ENGINE_EMULATOR_HOST: http://localhost:8080
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - "6379:6379"
    # restart: always

  auth_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password@1
      MYSQL_DATABASE: auth
    container_name: 'db-auth'
    volumes:
      - "./tmp/db/auth:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - 33306:3306
  group_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password@1
      MYSQL_DATABASE: group
    container_name: 'db-group'
    volumes:
      - "./tmp/db/group:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - 33307:3306

  activity_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password@1
      MYSQL_DATABASE: activity
    container_name: 'db-activity'
    volumes:
      - "./tmp/db/activity:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - 33308:3306

  notification_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password@1
      MYSQL_DATABASE: notification
    container_name: 'db-notification'
    volumes:
      - "./tmp/db/notification:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - 33309:3306

  plan_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password@1
      MYSQL_DATABASE: plan
    container_name: 'db-plan'
    volumes:
      - "./tmp/db/plan:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - 33310:3306

  chat_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password@1
      MYSQL_DATABASE: chat
    container_name: 'db-chat'
    volumes:
      - "./tmp/db/chat:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - 33311:3306
