version: '3.7'

services:

  gateway:
    build:
      context: backend/gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - 8080:8080

  auth:
    build:
      context: backend/auth
      dockerfile: build/Dockerfile
    container_name: auth
    volumes:
      - ./backend/auth:/app
    depends_on:
      - auth_db
      - redis

  auth_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password@1
      MYSQL_DATABASE: auth
    container_name: 'db-auth'
    volumes:
      - "./tmp/db/auth:/var/lib/mysql"
    ports:
      - 33306:3306

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    # restart: always

  group:
    build:
      context: backend/group
      dockerfile: build/Dockerfile
    container_name: group
    depends_on:
      - group_db
    

  group_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password@1
      MYSQL_DATABASE: group
    container_name: 'db-group'
    volumes:
      - "./tmp/db/group:/var/lib/mysql"
    ports:
      - 33307:3306

  activity:
    build:
      context: backend/activity
      dockerfile: build/Dockerfile
    container_name: activity
    depends_on:
      - activity_db

  activity_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password@1
      MYSQL_DATABASE: activity
    container_name: 'db-activity'
    volumes:
      - "./tmp/db/activity:/var/lib/mysql"
    ports:
      - 33308:3306

  notification:
    build:
      context: backend/notification
      dockerfile: build/Dockerfile
    container_name: notification
    depends_on:
      - notification_db
    ports:
      - 8000:8000
    
  notification_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password@1
      MYSQL_DATABASE: notification
    container_name: 'db-notification'
    volumes:
      - "./tmp/db/notification:/var/lib/mysql"
    ports:
      - 33309:3306

  gcloud-tasks-emulator:
    image: ghcr.io/aertje/cloud-tasks-emulator:latest
    command: -host 0.0.0.0 -port 8123 -queue "projects/daring-acumen-370401/locations/asia-southeast2/queues/test-queue1"
    ports:
      - "${TASKS_PORT:-8123}:8123"
    environment:
      APP_ENGINE_EMULATOR_HOST: http://localhost:8080
    
