version: '3.7'

services:
  sample:
    build:
      context: backend/sample
      dockerfile: build/Dockerfile
    container_name: sample
    ports:
      - 8081:8080
    depends_on:
      - sample_db

  sample_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password@1
      MYSQL_DATABASE: sample

  caller:
    build:
      context: backend/caller
      dockerfile: build/Dockerfile
    container_name: caller
    depends_on:
      - sample

  gateway:
    build:
      context: backend/gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - 8080:8080
  
  auth:
    build:
      context: backend/auth
      dockerfile: build/Dockerfile
    container_name: auth

  auth_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password@1
      MYSQL_DATABASE: auth
    container_name: 'db-auth'
    volumes:
      - "./tmp/db/auth:/var/lib/mysql"
    ports:
      - 33306:3306
