version: '3.7'

services:
  gateway:
    build:
      context: backend/gateway
      dockerfile: Dockerfile
    container_name: gateway
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - 8080:8080

  auth:
    build:
      context: backend/auth
      dockerfile: build/Dockerfile
    container_name: auth
    volumes:
      - ./backend/auth:/app
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    depends_on:
      - auth_db
      - redis

  group:
    build:
      context: backend/group
      dockerfile: build/Dockerfile
    container_name: group
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    depends_on:
      - group_db

  activity:
    build:
      context: backend/activity
      dockerfile: build/Dockerfile
    container_name: activity
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    depends_on:
      - activity_db
    environment:
      LISTEN_PORT: 8080
      DB_USERNAME: root
      DB_PASSWORD: password@1
      DB_HOST: activity_db
      DB_PORT: 3306
      DB_NAME: activity

  notification:
    build:
      context: backend/notification
      dockerfile: build/Dockerfile
    container_name: notification
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    depends_on:
      - notification_db
    ports:
      - 8000:8000

  plan:
    build:
      context: backend/plan
      dockerfile: build/Dockerfile
    container_name: plan
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    depends_on:
      - plan_db
    ports:
      - 8081:8080
    environment:
      LISTEN_PORT: 8080
      DB_USERNAME: root
      DB_PASSWORD: password@1
      DB_HOST: plan_db
      DB_PORT: 3306
      DB_NAME: plan

  gcloud-tasks-emulator:
    image: ghcr.io/aertje/cloud-tasks-emulator:latest
    command: -host 0.0.0.0 -port 8123 -queue "projects/daring-acumen-370401/locations/asia-southeast2/queues/test-queue1"
    ports:
      - "${TASKS_PORT:-8123}:8123"
    environment:
      APP_ENGINE_EMULATOR_HOST: http://localhost:8080
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - "6379:6379"
    # restart: always

  auth_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password@1
      MYSQL_DATABASE: auth
    container_name: 'db-auth'
    volumes:
      - "./tmp/db/auth:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - 33306:3306

  group_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password@1
      MYSQL_DATABASE: group
    container_name: 'db-group'
    volumes:
      - "./tmp/db/group:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - 33307:3306

  activity_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password@1
      MYSQL_DATABASE: activity
    container_name: 'db-activity'
    volumes:
      - "./tmp/db/activity:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - 33308:3306

  notification_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password@1
      MYSQL_DATABASE: notification
    container_name: 'db-notification'
    volumes:
      - "./tmp/db/notification:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - 33309:3306

  plan_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password@1
      MYSQL_DATABASE: plan
    container_name: 'db-plan'
    volumes:
      - "./tmp/db/plan:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - 33310:3306
