database:
 username: "root"
 password: "password@1"
 domain: "auth_db"
 port: "3306"
 name: "auth" 

grpc: 
 host: "0.0.0.0"
 port: "8080"
 network: "tcp"

cache:
 host: "redis"
 port: "6379"
 password: ""
 db: 0
 