// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/manhrev/runtracking/backend/event/pkg/ent/event"
	"github.com/manhrev/runtracking/backend/event/pkg/ent/groupzprogress"
	"github.com/manhrev/runtracking/backend/event/pkg/ent/predicate"
	"github.com/manhrev/runtracking/backend/event/pkg/ent/subevent"
)

// SubEventQuery is the builder for querying SubEvent entities.
type SubEventQuery struct {
	config
	ctx        *QueryContext
	order      []subevent.Order
	inters     []Interceptor
	predicates []predicate.SubEvent
	withEvent  *EventQuery
	withGroup  *GroupzProgressQuery
	withFKs    bool
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SubEventQuery builder.
func (seq *SubEventQuery) Where(ps ...predicate.SubEvent) *SubEventQuery {
	seq.predicates = append(seq.predicates, ps...)
	return seq
}

// Limit the number of records to be returned by this query.
func (seq *SubEventQuery) Limit(limit int) *SubEventQuery {
	seq.ctx.Limit = &limit
	return seq
}

// Offset to start from.
func (seq *SubEventQuery) Offset(offset int) *SubEventQuery {
	seq.ctx.Offset = &offset
	return seq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (seq *SubEventQuery) Unique(unique bool) *SubEventQuery {
	seq.ctx.Unique = &unique
	return seq
}

// Order specifies how the records should be ordered.
func (seq *SubEventQuery) Order(o ...subevent.Order) *SubEventQuery {
	seq.order = append(seq.order, o...)
	return seq
}

// QueryEvent chains the current query on the "event" edge.
func (seq *SubEventQuery) QueryEvent() *EventQuery {
	query := (&EventClient{config: seq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := seq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := seq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subevent.Table, subevent.FieldID, selector),
			sqlgraph.To(event.Table, event.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, subevent.EventTable, subevent.EventColumn),
		)
		fromU = sqlgraph.SetNeighbors(seq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGroup chains the current query on the "group" edge.
func (seq *SubEventQuery) QueryGroup() *GroupzProgressQuery {
	query := (&GroupzProgressClient{config: seq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := seq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := seq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subevent.Table, subevent.FieldID, selector),
			sqlgraph.To(groupzprogress.Table, groupzprogress.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, subevent.GroupTable, subevent.GroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(seq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SubEvent entity from the query.
// Returns a *NotFoundError when no SubEvent was found.
func (seq *SubEventQuery) First(ctx context.Context) (*SubEvent, error) {
	nodes, err := seq.Limit(1).All(setContextOp(ctx, seq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{subevent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (seq *SubEventQuery) FirstX(ctx context.Context) *SubEvent {
	node, err := seq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SubEvent ID from the query.
// Returns a *NotFoundError when no SubEvent ID was found.
func (seq *SubEventQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = seq.Limit(1).IDs(setContextOp(ctx, seq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{subevent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (seq *SubEventQuery) FirstIDX(ctx context.Context) int64 {
	id, err := seq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SubEvent entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SubEvent entity is found.
// Returns a *NotFoundError when no SubEvent entities are found.
func (seq *SubEventQuery) Only(ctx context.Context) (*SubEvent, error) {
	nodes, err := seq.Limit(2).All(setContextOp(ctx, seq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{subevent.Label}
	default:
		return nil, &NotSingularError{subevent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (seq *SubEventQuery) OnlyX(ctx context.Context) *SubEvent {
	node, err := seq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SubEvent ID in the query.
// Returns a *NotSingularError when more than one SubEvent ID is found.
// Returns a *NotFoundError when no entities are found.
func (seq *SubEventQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = seq.Limit(2).IDs(setContextOp(ctx, seq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{subevent.Label}
	default:
		err = &NotSingularError{subevent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (seq *SubEventQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := seq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SubEvents.
func (seq *SubEventQuery) All(ctx context.Context) ([]*SubEvent, error) {
	ctx = setContextOp(ctx, seq.ctx, "All")
	if err := seq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SubEvent, *SubEventQuery]()
	return withInterceptors[[]*SubEvent](ctx, seq, qr, seq.inters)
}

// AllX is like All, but panics if an error occurs.
func (seq *SubEventQuery) AllX(ctx context.Context) []*SubEvent {
	nodes, err := seq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SubEvent IDs.
func (seq *SubEventQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if seq.ctx.Unique == nil && seq.path != nil {
		seq.Unique(true)
	}
	ctx = setContextOp(ctx, seq.ctx, "IDs")
	if err = seq.Select(subevent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (seq *SubEventQuery) IDsX(ctx context.Context) []int64 {
	ids, err := seq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (seq *SubEventQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, seq.ctx, "Count")
	if err := seq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, seq, querierCount[*SubEventQuery](), seq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (seq *SubEventQuery) CountX(ctx context.Context) int {
	count, err := seq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (seq *SubEventQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, seq.ctx, "Exist")
	switch _, err := seq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (seq *SubEventQuery) ExistX(ctx context.Context) bool {
	exist, err := seq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SubEventQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (seq *SubEventQuery) Clone() *SubEventQuery {
	if seq == nil {
		return nil
	}
	return &SubEventQuery{
		config:     seq.config,
		ctx:        seq.ctx.Clone(),
		order:      append([]subevent.Order{}, seq.order...),
		inters:     append([]Interceptor{}, seq.inters...),
		predicates: append([]predicate.SubEvent{}, seq.predicates...),
		withEvent:  seq.withEvent.Clone(),
		withGroup:  seq.withGroup.Clone(),
		// clone intermediate query.
		sql:  seq.sql.Clone(),
		path: seq.path,
	}
}

// WithEvent tells the query-builder to eager-load the nodes that are connected to
// the "event" edge. The optional arguments are used to configure the query builder of the edge.
func (seq *SubEventQuery) WithEvent(opts ...func(*EventQuery)) *SubEventQuery {
	query := (&EventClient{config: seq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	seq.withEvent = query
	return seq
}

// WithGroup tells the query-builder to eager-load the nodes that are connected to
// the "group" edge. The optional arguments are used to configure the query builder of the edge.
func (seq *SubEventQuery) WithGroup(opts ...func(*GroupzProgressQuery)) *SubEventQuery {
	query := (&GroupzProgressClient{config: seq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	seq.withGroup = query
	return seq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SubEvent.Query().
//		GroupBy(subevent.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (seq *SubEventQuery) GroupBy(field string, fields ...string) *SubEventGroupBy {
	seq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SubEventGroupBy{build: seq}
	grbuild.flds = &seq.ctx.Fields
	grbuild.label = subevent.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.SubEvent.Query().
//		Select(subevent.FieldName).
//		Scan(ctx, &v)
//
func (seq *SubEventQuery) Select(fields ...string) *SubEventSelect {
	seq.ctx.Fields = append(seq.ctx.Fields, fields...)
	sbuild := &SubEventSelect{SubEventQuery: seq}
	sbuild.label = subevent.Label
	sbuild.flds, sbuild.scan = &seq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SubEventSelect configured with the given aggregations.
func (seq *SubEventQuery) Aggregate(fns ...AggregateFunc) *SubEventSelect {
	return seq.Select().Aggregate(fns...)
}

func (seq *SubEventQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range seq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, seq); err != nil {
				return err
			}
		}
	}
	for _, f := range seq.ctx.Fields {
		if !subevent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if seq.path != nil {
		prev, err := seq.path(ctx)
		if err != nil {
			return err
		}
		seq.sql = prev
	}
	return nil
}

func (seq *SubEventQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SubEvent, error) {
	var (
		nodes       = []*SubEvent{}
		withFKs     = seq.withFKs
		_spec       = seq.querySpec()
		loadedTypes = [2]bool{
			seq.withEvent != nil,
			seq.withGroup != nil,
		}
	)
	if seq.withEvent != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, subevent.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SubEvent).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SubEvent{config: seq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(seq.modifiers) > 0 {
		_spec.Modifiers = seq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, seq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := seq.withEvent; query != nil {
		if err := seq.loadEvent(ctx, query, nodes, nil,
			func(n *SubEvent, e *Event) { n.Edges.Event = e }); err != nil {
			return nil, err
		}
	}
	if query := seq.withGroup; query != nil {
		if err := seq.loadGroup(ctx, query, nodes,
			func(n *SubEvent) { n.Edges.Group = []*GroupzProgress{} },
			func(n *SubEvent, e *GroupzProgress) { n.Edges.Group = append(n.Edges.Group, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (seq *SubEventQuery) loadEvent(ctx context.Context, query *EventQuery, nodes []*SubEvent, init func(*SubEvent), assign func(*SubEvent, *Event)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*SubEvent)
	for i := range nodes {
		if nodes[i].event_subevents == nil {
			continue
		}
		fk := *nodes[i].event_subevents
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(event.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "event_subevents" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (seq *SubEventQuery) loadGroup(ctx context.Context, query *GroupzProgressQuery, nodes []*SubEvent, init func(*SubEvent), assign func(*SubEvent, *GroupzProgress)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*SubEvent)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.GroupzProgress(func(s *sql.Selector) {
		s.Where(sql.InValues(subevent.GroupColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.sub_event_group
		if fk == nil {
			return fmt.Errorf(`foreign-key "sub_event_group" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "sub_event_group" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (seq *SubEventQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := seq.querySpec()
	if len(seq.modifiers) > 0 {
		_spec.Modifiers = seq.modifiers
	}
	_spec.Node.Columns = seq.ctx.Fields
	if len(seq.ctx.Fields) > 0 {
		_spec.Unique = seq.ctx.Unique != nil && *seq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, seq.driver, _spec)
}

func (seq *SubEventQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(subevent.Table, subevent.Columns, sqlgraph.NewFieldSpec(subevent.FieldID, field.TypeInt64))
	_spec.From = seq.sql
	if unique := seq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if seq.path != nil {
		_spec.Unique = true
	}
	if fields := seq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subevent.FieldID)
		for i := range fields {
			if fields[i] != subevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := seq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := seq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := seq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := seq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (seq *SubEventQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(seq.driver.Dialect())
	t1 := builder.Table(subevent.Table)
	columns := seq.ctx.Fields
	if len(columns) == 0 {
		columns = subevent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if seq.sql != nil {
		selector = seq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if seq.ctx.Unique != nil && *seq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range seq.modifiers {
		m(selector)
	}
	for _, p := range seq.predicates {
		p(selector)
	}
	for _, p := range seq.order {
		p(selector)
	}
	if offset := seq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := seq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (seq *SubEventQuery) Modify(modifiers ...func(s *sql.Selector)) *SubEventSelect {
	seq.modifiers = append(seq.modifiers, modifiers...)
	return seq.Select()
}

// SubEventGroupBy is the group-by builder for SubEvent entities.
type SubEventGroupBy struct {
	selector
	build *SubEventQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (segb *SubEventGroupBy) Aggregate(fns ...AggregateFunc) *SubEventGroupBy {
	segb.fns = append(segb.fns, fns...)
	return segb
}

// Scan applies the selector query and scans the result into the given value.
func (segb *SubEventGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, segb.build.ctx, "GroupBy")
	if err := segb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubEventQuery, *SubEventGroupBy](ctx, segb.build, segb, segb.build.inters, v)
}

func (segb *SubEventGroupBy) sqlScan(ctx context.Context, root *SubEventQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(segb.fns))
	for _, fn := range segb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*segb.flds)+len(segb.fns))
		for _, f := range *segb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*segb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := segb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SubEventSelect is the builder for selecting fields of SubEvent entities.
type SubEventSelect struct {
	*SubEventQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ses *SubEventSelect) Aggregate(fns ...AggregateFunc) *SubEventSelect {
	ses.fns = append(ses.fns, fns...)
	return ses
}

// Scan applies the selector query and scans the result into the given value.
func (ses *SubEventSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ses.ctx, "Select")
	if err := ses.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubEventQuery, *SubEventSelect](ctx, ses.SubEventQuery, ses, ses.inters, v)
}

func (ses *SubEventSelect) sqlScan(ctx context.Context, root *SubEventQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ses.fns))
	for _, fn := range ses.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ses.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ses.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ses *SubEventSelect) Modify(modifiers ...func(s *sql.Selector)) *SubEventSelect {
	ses.modifiers = append(ses.modifiers, modifiers...)
	return ses
}
