// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/manhrev/runtracking/backend/group/pkg/ent/challenge"
	"github.com/manhrev/runtracking/backend/group/pkg/ent/challengemember"
	"github.com/manhrev/runtracking/backend/group/pkg/ent/member"
)

// ChallengeMember is the model entity for the ChallengeMember schema.
type ChallengeMember struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Point holds the value of the "point" field.
	Point int64 `json:"point,omitempty"`
	// MemberID holds the value of the "member_id" field.
	MemberID int64 `json:"member_id,omitempty"`
	// ChallengeID holds the value of the "challenge_id" field.
	ChallengeID int64 `json:"challenge_id,omitempty"`
	// IsCompleted holds the value of the "is_completed" field.
	IsCompleted bool `json:"is_completed,omitempty"`
	// TimeCompleted holds the value of the "time_completed" field.
	TimeCompleted time.Time `json:"time_completed,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChallengeMemberQuery when eager-loading is set.
	Edges ChallengeMemberEdges `json:"edges"`
}

// ChallengeMemberEdges holds the relations/edges for other nodes in the graph.
type ChallengeMemberEdges struct {
	// ChallengeMemberRules holds the value of the challenge_member_rules edge.
	ChallengeMemberRules []*ChallengeMemberRule `json:"challenge_member_rules,omitempty"`
	// Challenge holds the value of the challenge edge.
	Challenge *Challenge `json:"challenge,omitempty"`
	// Member holds the value of the member edge.
	Member *Member `json:"member,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ChallengeMemberRulesOrErr returns the ChallengeMemberRules value or an error if the edge
// was not loaded in eager-loading.
func (e ChallengeMemberEdges) ChallengeMemberRulesOrErr() ([]*ChallengeMemberRule, error) {
	if e.loadedTypes[0] {
		return e.ChallengeMemberRules, nil
	}
	return nil, &NotLoadedError{edge: "challenge_member_rules"}
}

// ChallengeOrErr returns the Challenge value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChallengeMemberEdges) ChallengeOrErr() (*Challenge, error) {
	if e.loadedTypes[1] {
		if e.Challenge == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: challenge.Label}
		}
		return e.Challenge, nil
	}
	return nil, &NotLoadedError{edge: "challenge"}
}

// MemberOrErr returns the Member value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChallengeMemberEdges) MemberOrErr() (*Member, error) {
	if e.loadedTypes[2] {
		if e.Member == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: member.Label}
		}
		return e.Member, nil
	}
	return nil, &NotLoadedError{edge: "member"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChallengeMember) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case challengemember.FieldIsCompleted:
			values[i] = new(sql.NullBool)
		case challengemember.FieldID, challengemember.FieldPoint, challengemember.FieldMemberID, challengemember.FieldChallengeID:
			values[i] = new(sql.NullInt64)
		case challengemember.FieldTimeCompleted, challengemember.FieldCreatedAt, challengemember.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type ChallengeMember", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChallengeMember fields.
func (cm *ChallengeMember) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case challengemember.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			cm.ID = int64(value.Int64)
		case challengemember.FieldPoint:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field point", values[i])
			} else if value.Valid {
				cm.Point = value.Int64
			}
		case challengemember.FieldMemberID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field member_id", values[i])
			} else if value.Valid {
				cm.MemberID = value.Int64
			}
		case challengemember.FieldChallengeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field challenge_id", values[i])
			} else if value.Valid {
				cm.ChallengeID = value.Int64
			}
		case challengemember.FieldIsCompleted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_completed", values[i])
			} else if value.Valid {
				cm.IsCompleted = value.Bool
			}
		case challengemember.FieldTimeCompleted:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field time_completed", values[i])
			} else if value.Valid {
				cm.TimeCompleted = value.Time
			}
		case challengemember.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				cm.CreatedAt = value.Time
			}
		case challengemember.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				cm.UpdatedAt = value.Time
			}
		}
	}
	return nil
}

// QueryChallengeMemberRules queries the "challenge_member_rules" edge of the ChallengeMember entity.
func (cm *ChallengeMember) QueryChallengeMemberRules() *ChallengeMemberRuleQuery {
	return NewChallengeMemberClient(cm.config).QueryChallengeMemberRules(cm)
}

// QueryChallenge queries the "challenge" edge of the ChallengeMember entity.
func (cm *ChallengeMember) QueryChallenge() *ChallengeQuery {
	return NewChallengeMemberClient(cm.config).QueryChallenge(cm)
}

// QueryMember queries the "member" edge of the ChallengeMember entity.
func (cm *ChallengeMember) QueryMember() *MemberQuery {
	return NewChallengeMemberClient(cm.config).QueryMember(cm)
}

// Update returns a builder for updating this ChallengeMember.
// Note that you need to call ChallengeMember.Unwrap() before calling this method if this ChallengeMember
// was returned from a transaction, and the transaction was committed or rolled back.
func (cm *ChallengeMember) Update() *ChallengeMemberUpdateOne {
	return NewChallengeMemberClient(cm.config).UpdateOne(cm)
}

// Unwrap unwraps the ChallengeMember entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (cm *ChallengeMember) Unwrap() *ChallengeMember {
	_tx, ok := cm.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChallengeMember is not a transactional entity")
	}
	cm.config.driver = _tx.drv
	return cm
}

// String implements the fmt.Stringer.
func (cm *ChallengeMember) String() string {
	var builder strings.Builder
	builder.WriteString("ChallengeMember(")
	builder.WriteString(fmt.Sprintf("id=%v, ", cm.ID))
	builder.WriteString("point=")
	builder.WriteString(fmt.Sprintf("%v", cm.Point))
	builder.WriteString(", ")
	builder.WriteString("member_id=")
	builder.WriteString(fmt.Sprintf("%v", cm.MemberID))
	builder.WriteString(", ")
	builder.WriteString("challenge_id=")
	builder.WriteString(fmt.Sprintf("%v", cm.ChallengeID))
	builder.WriteString(", ")
	builder.WriteString("is_completed=")
	builder.WriteString(fmt.Sprintf("%v", cm.IsCompleted))
	builder.WriteString(", ")
	builder.WriteString("time_completed=")
	builder.WriteString(cm.TimeCompleted.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(cm.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(cm.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ChallengeMembers is a parsable slice of ChallengeMember.
type ChallengeMembers []*ChallengeMember

func (cm ChallengeMembers) config(cfg config) {
	for _i := range cm {
		cm[_i].config = cfg
	}
}
