// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/manhrev/runtracking/backend/group/pkg/ent/season"
	"github.com/manhrev/runtracking/backend/group/pkg/ent/seasonmember"
)

// SeasonCreate is the builder for creating a Season entity.
type SeasonCreate struct {
	config
	mutation *SeasonMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (sc *SeasonCreate) SetName(s string) *SeasonCreate {
	sc.mutation.SetName(s)
	return sc
}

// SetNillableName sets the "name" field if the given value is not nil.
func (sc *SeasonCreate) SetNillableName(s *string) *SeasonCreate {
	if s != nil {
		sc.SetName(*s)
	}
	return sc
}

// SetDescription sets the "description" field.
func (sc *SeasonCreate) SetDescription(s string) *SeasonCreate {
	sc.mutation.SetDescription(s)
	return sc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (sc *SeasonCreate) SetNillableDescription(s *string) *SeasonCreate {
	if s != nil {
		sc.SetDescription(*s)
	}
	return sc
}

// SetPicture sets the "picture" field.
func (sc *SeasonCreate) SetPicture(s string) *SeasonCreate {
	sc.mutation.SetPicture(s)
	return sc
}

// SetNillablePicture sets the "picture" field if the given value is not nil.
func (sc *SeasonCreate) SetNillablePicture(s *string) *SeasonCreate {
	if s != nil {
		sc.SetPicture(*s)
	}
	return sc
}

// SetCreatedAt sets the "created_at" field.
func (sc *SeasonCreate) SetCreatedAt(t time.Time) *SeasonCreate {
	sc.mutation.SetCreatedAt(t)
	return sc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sc *SeasonCreate) SetNillableCreatedAt(t *time.Time) *SeasonCreate {
	if t != nil {
		sc.SetCreatedAt(*t)
	}
	return sc
}

// SetUpdatedAt sets the "updated_at" field.
func (sc *SeasonCreate) SetUpdatedAt(t time.Time) *SeasonCreate {
	sc.mutation.SetUpdatedAt(t)
	return sc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (sc *SeasonCreate) SetNillableUpdatedAt(t *time.Time) *SeasonCreate {
	if t != nil {
		sc.SetUpdatedAt(*t)
	}
	return sc
}

// SetStartDate sets the "start_date" field.
func (sc *SeasonCreate) SetStartDate(t time.Time) *SeasonCreate {
	sc.mutation.SetStartDate(t)
	return sc
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (sc *SeasonCreate) SetNillableStartDate(t *time.Time) *SeasonCreate {
	if t != nil {
		sc.SetStartDate(*t)
	}
	return sc
}

// SetEndDate sets the "end_date" field.
func (sc *SeasonCreate) SetEndDate(t time.Time) *SeasonCreate {
	sc.mutation.SetEndDate(t)
	return sc
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (sc *SeasonCreate) SetNillableEndDate(t *time.Time) *SeasonCreate {
	if t != nil {
		sc.SetEndDate(*t)
	}
	return sc
}

// SetIsCurrent sets the "is_current" field.
func (sc *SeasonCreate) SetIsCurrent(b bool) *SeasonCreate {
	sc.mutation.SetIsCurrent(b)
	return sc
}

// SetNillableIsCurrent sets the "is_current" field if the given value is not nil.
func (sc *SeasonCreate) SetNillableIsCurrent(b *bool) *SeasonCreate {
	if b != nil {
		sc.SetIsCurrent(*b)
	}
	return sc
}

// SetID sets the "id" field.
func (sc *SeasonCreate) SetID(i int64) *SeasonCreate {
	sc.mutation.SetID(i)
	return sc
}

// AddSeasonMemberIDs adds the "season_members" edge to the SeasonMember entity by IDs.
func (sc *SeasonCreate) AddSeasonMemberIDs(ids ...int64) *SeasonCreate {
	sc.mutation.AddSeasonMemberIDs(ids...)
	return sc
}

// AddSeasonMembers adds the "season_members" edges to the SeasonMember entity.
func (sc *SeasonCreate) AddSeasonMembers(s ...*SeasonMember) *SeasonCreate {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return sc.AddSeasonMemberIDs(ids...)
}

// Mutation returns the SeasonMutation object of the builder.
func (sc *SeasonCreate) Mutation() *SeasonMutation {
	return sc.mutation
}

// Save creates the Season in the database.
func (sc *SeasonCreate) Save(ctx context.Context) (*Season, error) {
	sc.defaults()
	return withHooks[*Season, SeasonMutation](ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SeasonCreate) SaveX(ctx context.Context) *Season {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SeasonCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SeasonCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *SeasonCreate) defaults() {
	if _, ok := sc.mutation.Picture(); !ok {
		v := season.DefaultPicture
		sc.mutation.SetPicture(v)
	}
	if _, ok := sc.mutation.CreatedAt(); !ok {
		v := season.DefaultCreatedAt()
		sc.mutation.SetCreatedAt(v)
	}
	if _, ok := sc.mutation.UpdatedAt(); !ok {
		v := season.DefaultUpdatedAt()
		sc.mutation.SetUpdatedAt(v)
	}
	if _, ok := sc.mutation.IsCurrent(); !ok {
		v := season.DefaultIsCurrent
		sc.mutation.SetIsCurrent(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SeasonCreate) check() error {
	if _, ok := sc.mutation.Picture(); !ok {
		return &ValidationError{Name: "picture", err: errors.New(`ent: missing required field "Season.picture"`)}
	}
	if _, ok := sc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Season.created_at"`)}
	}
	if _, ok := sc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Season.updated_at"`)}
	}
	if _, ok := sc.mutation.IsCurrent(); !ok {
		return &ValidationError{Name: "is_current", err: errors.New(`ent: missing required field "Season.is_current"`)}
	}
	return nil
}

func (sc *SeasonCreate) sqlSave(ctx context.Context) (*Season, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *SeasonCreate) createSpec() (*Season, *sqlgraph.CreateSpec) {
	var (
		_node = &Season{config: sc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: season.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: season.FieldID,
			},
		}
	)
	if id, ok := sc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := sc.mutation.Name(); ok {
		_spec.SetField(season.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := sc.mutation.Description(); ok {
		_spec.SetField(season.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := sc.mutation.Picture(); ok {
		_spec.SetField(season.FieldPicture, field.TypeString, value)
		_node.Picture = value
	}
	if value, ok := sc.mutation.CreatedAt(); ok {
		_spec.SetField(season.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := sc.mutation.UpdatedAt(); ok {
		_spec.SetField(season.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := sc.mutation.StartDate(); ok {
		_spec.SetField(season.FieldStartDate, field.TypeTime, value)
		_node.StartDate = value
	}
	if value, ok := sc.mutation.EndDate(); ok {
		_spec.SetField(season.FieldEndDate, field.TypeTime, value)
		_node.EndDate = value
	}
	if value, ok := sc.mutation.IsCurrent(); ok {
		_spec.SetField(season.FieldIsCurrent, field.TypeBool, value)
		_node.IsCurrent = value
	}
	if nodes := sc.mutation.SeasonMembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   season.SeasonMembersTable,
			Columns: []string{season.SeasonMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt64,
					Column: seasonmember.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SeasonCreateBulk is the builder for creating many Season entities in bulk.
type SeasonCreateBulk struct {
	config
	builders []*SeasonCreate
}

// Save creates the Season entities in the database.
func (scb *SeasonCreateBulk) Save(ctx context.Context) ([]*Season, error) {
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Season, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SeasonMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SeasonCreateBulk) SaveX(ctx context.Context) []*Season {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SeasonCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SeasonCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
