// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/manhrev/runtracking/backend/notification/pkg/ent/notification"
)

// Notification is the model entity for the Notification schema.
type Notification struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Message holds the value of the "message" field.
	Message string `json:"message,omitempty"`
	// Type holds the value of the "type" field.
	Type int64 `json:"type,omitempty"`
	// ReceivedID holds the value of the "received_id" field.
	ReceivedID int64 `json:"received_id,omitempty"`
	// ScheduledTime holds the value of the "scheduled_time" field.
	ScheduledTime time.Time `json:"scheduled_time,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the NotificationQuery when eager-loading is set.
	Edges NotificationEdges `json:"edges"`
}

// NotificationEdges holds the relations/edges for other nodes in the graph.
type NotificationEdges struct {
	// NotificationUsers holds the value of the notification_users edge.
	NotificationUsers []*NotificationUser `json:"notification_users,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// NotificationUsersOrErr returns the NotificationUsers value or an error if the edge
// was not loaded in eager-loading.
func (e NotificationEdges) NotificationUsersOrErr() ([]*NotificationUser, error) {
	if e.loadedTypes[0] {
		return e.NotificationUsers, nil
	}
	return nil, &NotLoadedError{edge: "notification_users"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Notification) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case notification.FieldID, notification.FieldType, notification.FieldReceivedID:
			values[i] = new(sql.NullInt64)
		case notification.FieldMessage:
			values[i] = new(sql.NullString)
		case notification.FieldScheduledTime:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Notification", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Notification fields.
func (n *Notification) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case notification.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			n.ID = int64(value.Int64)
		case notification.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				n.Message = value.String
			}
		case notification.FieldType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				n.Type = value.Int64
			}
		case notification.FieldReceivedID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field received_id", values[i])
			} else if value.Valid {
				n.ReceivedID = value.Int64
			}
		case notification.FieldScheduledTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field scheduled_time", values[i])
			} else if value.Valid {
				n.ScheduledTime = value.Time
			}
		}
	}
	return nil
}

// QueryNotificationUsers queries the "notification_users" edge of the Notification entity.
func (n *Notification) QueryNotificationUsers() *NotificationUserQuery {
	return NewNotificationClient(n.config).QueryNotificationUsers(n)
}

// Update returns a builder for updating this Notification.
// Note that you need to call Notification.Unwrap() before calling this method if this Notification
// was returned from a transaction, and the transaction was committed or rolled back.
func (n *Notification) Update() *NotificationUpdateOne {
	return NewNotificationClient(n.config).UpdateOne(n)
}

// Unwrap unwraps the Notification entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (n *Notification) Unwrap() *Notification {
	_tx, ok := n.config.driver.(*txDriver)
	if !ok {
		panic("ent: Notification is not a transactional entity")
	}
	n.config.driver = _tx.drv
	return n
}

// String implements the fmt.Stringer.
func (n *Notification) String() string {
	var builder strings.Builder
	builder.WriteString("Notification(")
	builder.WriteString(fmt.Sprintf("id=%v, ", n.ID))
	builder.WriteString("message=")
	builder.WriteString(n.Message)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", n.Type))
	builder.WriteString(", ")
	builder.WriteString("received_id=")
	builder.WriteString(fmt.Sprintf("%v", n.ReceivedID))
	builder.WriteString(", ")
	builder.WriteString("scheduled_time=")
	builder.WriteString(n.ScheduledTime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Notifications is a parsable slice of Notification.
type Notifications []*Notification

func (n Notifications) config(cfg config) {
	for _i := range n {
		n[_i].config = cfg
	}
}
