// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: api/notification.proto

package notification

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NotificationClient is the client API for Notification service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationClient interface {
	CheckIfExistOrSaveExpoPushToken(ctx context.Context, in *ExpoPushTokenRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveExpoPushToken(ctx context.Context, in *ExpoPushTokenRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListNotificationInfo(ctx context.Context, in *ListNotificationInfoRequest, opts ...grpc.CallOption) (*ListNotificationInfoReply, error)
	DeleteNotificationInfo(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*IdReply, error)
	UpdateNotificationInfo(ctx context.Context, in *UpdateNotificationInfoRequest, opts ...grpc.CallOption) (*UpdateNotificationInfoReply, error)
}

type notificationClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationClient(cc grpc.ClientConnInterface) NotificationClient {
	return &notificationClient{cc}
}

func (c *notificationClient) CheckIfExistOrSaveExpoPushToken(ctx context.Context, in *ExpoPushTokenRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/notification.Notification/CheckIfExistOrSaveExpoPushToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) RemoveExpoPushToken(ctx context.Context, in *ExpoPushTokenRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/notification.Notification/RemoveExpoPushToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) ListNotificationInfo(ctx context.Context, in *ListNotificationInfoRequest, opts ...grpc.CallOption) (*ListNotificationInfoReply, error) {
	out := new(ListNotificationInfoReply)
	err := c.cc.Invoke(ctx, "/notification.Notification/ListNotificationInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) DeleteNotificationInfo(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*IdReply, error) {
	out := new(IdReply)
	err := c.cc.Invoke(ctx, "/notification.Notification/DeleteNotificationInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) UpdateNotificationInfo(ctx context.Context, in *UpdateNotificationInfoRequest, opts ...grpc.CallOption) (*UpdateNotificationInfoReply, error) {
	out := new(UpdateNotificationInfoReply)
	err := c.cc.Invoke(ctx, "/notification.Notification/UpdateNotificationInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServer is the server API for Notification service.
// All implementations must embed UnimplementedNotificationServer
// for forward compatibility
type NotificationServer interface {
	CheckIfExistOrSaveExpoPushToken(context.Context, *ExpoPushTokenRequest) (*emptypb.Empty, error)
	RemoveExpoPushToken(context.Context, *ExpoPushTokenRequest) (*emptypb.Empty, error)
	ListNotificationInfo(context.Context, *ListNotificationInfoRequest) (*ListNotificationInfoReply, error)
	DeleteNotificationInfo(context.Context, *IdRequest) (*IdReply, error)
	UpdateNotificationInfo(context.Context, *UpdateNotificationInfoRequest) (*UpdateNotificationInfoReply, error)
	mustEmbedUnimplementedNotificationServer()
}

// UnimplementedNotificationServer must be embedded to have forward compatible implementations.
type UnimplementedNotificationServer struct {
}

func (UnimplementedNotificationServer) CheckIfExistOrSaveExpoPushToken(context.Context, *ExpoPushTokenRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckIfExistOrSaveExpoPushToken not implemented")
}
func (UnimplementedNotificationServer) RemoveExpoPushToken(context.Context, *ExpoPushTokenRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveExpoPushToken not implemented")
}
func (UnimplementedNotificationServer) ListNotificationInfo(context.Context, *ListNotificationInfoRequest) (*ListNotificationInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNotificationInfo not implemented")
}
func (UnimplementedNotificationServer) DeleteNotificationInfo(context.Context, *IdRequest) (*IdReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNotificationInfo not implemented")
}
func (UnimplementedNotificationServer) UpdateNotificationInfo(context.Context, *UpdateNotificationInfoRequest) (*UpdateNotificationInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNotificationInfo not implemented")
}
func (UnimplementedNotificationServer) mustEmbedUnimplementedNotificationServer() {}

// UnsafeNotificationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServer will
// result in compilation errors.
type UnsafeNotificationServer interface {
	mustEmbedUnimplementedNotificationServer()
}

func RegisterNotificationServer(s grpc.ServiceRegistrar, srv NotificationServer) {
	s.RegisterService(&Notification_ServiceDesc, srv)
}

func _Notification_CheckIfExistOrSaveExpoPushToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpoPushTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).CheckIfExistOrSaveExpoPushToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.Notification/CheckIfExistOrSaveExpoPushToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).CheckIfExistOrSaveExpoPushToken(ctx, req.(*ExpoPushTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_RemoveExpoPushToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpoPushTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).RemoveExpoPushToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.Notification/RemoveExpoPushToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).RemoveExpoPushToken(ctx, req.(*ExpoPushTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_ListNotificationInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNotificationInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).ListNotificationInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.Notification/ListNotificationInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).ListNotificationInfo(ctx, req.(*ListNotificationInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_DeleteNotificationInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).DeleteNotificationInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.Notification/DeleteNotificationInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).DeleteNotificationInfo(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_UpdateNotificationInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNotificationInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).UpdateNotificationInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.Notification/UpdateNotificationInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).UpdateNotificationInfo(ctx, req.(*UpdateNotificationInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Notification_ServiceDesc is the grpc.ServiceDesc for Notification service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Notification_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification.Notification",
	HandlerType: (*NotificationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckIfExistOrSaveExpoPushToken",
			Handler:    _Notification_CheckIfExistOrSaveExpoPushToken_Handler,
		},
		{
			MethodName: "RemoveExpoPushToken",
			Handler:    _Notification_RemoveExpoPushToken_Handler,
		},
		{
			MethodName: "ListNotificationInfo",
			Handler:    _Notification_ListNotificationInfo_Handler,
		},
		{
			MethodName: "DeleteNotificationInfo",
			Handler:    _Notification_DeleteNotificationInfo_Handler,
		},
		{
			MethodName: "UpdateNotificationInfo",
			Handler:    _Notification_UpdateNotificationInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/notification.proto",
}
